#include "globals.h"

void closeSideAWP () {
    chassis.drive_dist(40);
    chassis.turn_to_angle(-70);
    intake.move_voltage(-MAX_VOLT);
    wait(200);
    chassis.drive_dist(-7);
    chassis.turn_to_angle(7);
    intake.move_voltage(MAX_VOLT);
    chassis.drive_dist(12);
    intake.move_voltage(0);
    chassis.drive_dist(-3);
    chassis.turn_to_angle(90);
    chassis.drive_dist(-15);
    chassis.drive_dist(25);
    chassis.turn_to_angle(-135);
    chassis.drive_dist(53);
    chassis.turn_to_angle(-45);
    flapjacks.set_value(true);
    chassis.drive_dist(-5);
    chassis.left_swing_to_angle(-90);
    flapjacks.set_value(false);
    wait(200);
    chassis.turn_to_angle(130);
    intake.move_voltage(-MAX_VOLT);
    chassis.drive_dist(40, 90);
    intake.move_voltage(0);
}

void farSide () {
    intake.move_voltage(MAX_VOLT);
    chassis.drive_dist(10);
    intake.move_voltage(0);
    chassis.drive_dist(-30);
    chassis.left_swing_to_angle(-45);
    flapjacks.set_value(true);
    chassis.drive_dist(-13);
    chassis.left_swing_to_angle(-90);
    flapjacks.set_value(false);
    wait(500);
    chassis.turn_to_angle(135);
    intake.move_voltage(-MAX_VOLT);
    wait(500);
    chassis.drive_dist(12, 90);
    chassis.drive_dist(-10, 90);
    intake.move_voltage(MAX_VOLT);
    chassis.turn_to_angle(20);
    chassis.drive_dist(50);
    intake.move_voltage(0);
    chassis.drive_dist(-15);
    chassis.turn_to_angle(140);
    intake.move_voltage(-MAX_VOLT);
    wait(750);
    chassis.drive_dist(5);
    chassis.right_swing_to_angle(35);
    intake.move_voltage(MAX_VOLT);
    chassis.drive_dist(30);
    intake.move_voltage(0);
    chassis.drive_dist(-5);
    flapjacks.set_value(true);
    chassis.drive_dist(-28, 0);
    chassis.drive_dist(10);
    flapjacks.set_value(false);
    // wait(500);
    chassis.turn_to_angle(180);
    intake.move_voltage(-MAX_VOLT);
    chassis.drive_dist(7);
    intake.move_voltage(0);
    chassis.drive_dist(-5);
    pros::lcd::lcd_btn_cb_fn_t();
}

void progSkills () {
    flapjacks.set_value(true);
    wait(200);
    flapjacks.set_value(false);
    chassis.turn_to_angle(150);
    chassis.drive_dist(-7, 150);
    wait(500);
    cata.move_voltage(-MAX_VOLT * 0.9);
    wait(30000); 
    cata.move_voltage(0);
    chassis.drive_dist(1, 150);
    chassis.turn_to_angle(-130);
    chassis.drive_dist(-25, -130);
    wait(500);
    chassis.drive_dist(25, -130);
    chassis.turn_to_angle(-180);
    chassis.drive_dist(77, -180);
    chassis.turn_to_angle(90);
    chassis.drive_dist(21, 90);
    chassis.turn_to_angle(0);
    chassis.drive_dist(21, 0);
    chassis.turn_to_angle(90);
    chassis.drive_dist(30, 90);
    chassis.turn_to_angle(180);
    // flapjacks.set_value(true);
    chassis.drive_dist(25, 180);
    wait(500);
    chassis.drive_dist(-30, 180);
    flapjacks.set_value(false);
    chassis.turn_to_angle(90);
    chassis.drive_dist(20, 90);
    chassis.turn_to_angle(180);
    // flapjacks.set_value(true);
    chassis.drive_dist(30, 180);
    wait(500);
    chassis.drive_dist(-30, 180);
}